version: '3.8'
services:
  # dev-db:
  #   image: postgres:14.2-alpine
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: postgres
  #   networks:
  #     - kay
  test-db:
    image: postgres:13
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_test
    networks:
      - kay
networks:
  kay: