export const data = {
  user: [{ email: 'nskwbn@gmail.com', password: '123', id: '1' }],
  overview: {
    totalCampaigns: 33,
    successfulCampaign: 30,
    pending: 3,
    failed: 0,
  },
  operators: [
    {
      name: 'Omakar',
      role: 'Admin',
    },
    {
      name: 'Ravi Krishna',
      role: 'User',
    },
    {
      name: 'Sai Manohar',
      role: 'User',
    },
    {
      name: 'Sai Krishna',
      role: 'User',
    },
    {
      name: 'Ravi Manohar',
      role: 'User',
    },
    {
      name: 'Omakar Krishnar',
      role: 'User',
    },
    {
      name: 'Omakar Manohar',
      role: 'User',
    },
    {
      name: 'Jhanavi',
      role: 'User',
    },
    {
      name: 'Omakar Jhanavi',
      role: 'User',
    },
  ],
  'top-conversations': [
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 8,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 5,
      NoOfClicks: 9,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 3,
      NoOfClicks: 12,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 6,
      NoOfClicks: 9,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 8,
      NoOfClicks: 18,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 6,
      NoOfClicks: 7,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 4,
      NoOfClicks: 7,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 4,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 6,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 8,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 8,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 8,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 8,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 8,
      Actions: 'Visit Store',
    },
    {
      TemplateTitle: 'Title 02-03-2023',
      SentDay: '02/03/2023',
      Category: '50% Offer',
      Recipients: 2,
      NoOfClicks: 8,
      Actions: 'Visit Store',
    },
  ],
  contacts: [
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
    {
      name: 'Omakar',
      contactNumber: '9876543210',
      createdDate: '02 feb 2023',
      campaign: 'Yes',
    },
  ],
  chats: [
    {
      id: 1,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 2,
      name: 'Alex Smith',
      lastMessage: 'Lorem blaah is smiply ',
      unread: 2,
      lastActive: '2:30AM',
    },
    {
      id: 3,
      name: 'Joe haze',
      lastMessage: 'Random text',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 4,
      name: 'Alex aze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 5,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 6,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 7,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 8,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 9,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 10,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 11,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
    {
      id: 12,
      name: 'Alex haze',
      lastMessage: 'Lorem Ipsum is smiply dummy',
      unread: 2,
      lastActive: '2:30PM',
    },
  ],
  messages: [
    {
      id: '1',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '2',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '3',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '4',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '5',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '6',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '7',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '8',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '9',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '10',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '11',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
    {
      id: '12',
      data: [
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
        { from: 'message from me', to: 'message to me' },
      ],
    },
  ],
};
